version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - db
      - kibana
  elasticsearch:
    container_name: elastic
    image: elasticsearch:8.8.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      - net

  kibana:
    container_name: kibana
    image: kibana:8.8.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - net

  db:
    image: postgres:15.3-alpine3.18
    container_name: db_app
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - net
networks:
  net:
    driver: bridge