version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres:15.1
    container_name: db_app
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - net

networks:
  net: