"""DB creation

Revision ID: 25dab14b3fc5
Revises: ac21454c7761
Create Date: 2023-06-23 16:16:36.731081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25dab14b3fc5'
down_revision = 'ac21454c7761'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
