"""Table creation

Revision ID: 7698ee703aef
Revises: 
Create Date: 2023-06-15 16:53:30.098280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7698ee703aef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rubrics', sa.String(length=45), nullable=False),
    sa.Column('doc_text', sa.Text(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docs')
    # ### end Alembic commands ###
