"""Table using class

Revision ID: affb3e117f42
Revises: 7698ee703aef
Create Date: 2023-06-15 17:36:37.050672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'affb3e117f42'
down_revision = '7698ee703aef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rubrics', sa.String(length=45), nullable=False),
    sa.Column('doc_text', sa.Text(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('docs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rubrics', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('doc_text', mysql.TEXT(), nullable=False),
    sa.Column('created_date', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('posts')
    # ### end Alembic commands ###
